//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safety.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DefaultResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Safety.Domain.Resources.DefaultResource", typeof(DefaultResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string ALT_LABEL {
            get {
                return ResourceManager.GetString("ALT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string ALTITUDE_LABEL {
            get {
                return ResourceManager.GetString("ALTITUDE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string CONFIG {
            get {
                return ResourceManager.GetString("CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português-BR.
        /// </summary>
        public static string CULTURE_INFO_PTBR {
            get {
                return ResourceManager.GetString("CULTURE_INFO_PTBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixar.
        /// </summary>
        public static string DOWNLOAD {
            get {
                return ResourceManager.GetString("DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixar Tudo.
        /// </summary>
        public static string DOWNLOAD_ALL {
            get {
                return ResourceManager.GetString("DOWNLOAD_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lat.
        /// </summary>
        public static string LAT_LABEL {
            get {
                return ResourceManager.GetString("LAT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string LATITUTE_LABEL {
            get {
                return ResourceManager.GetString("LATITUTE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho Compactado:.
        /// </summary>
        public static string LENGTH_COMPRESS_LABEL {
            get {
                return ResourceManager.GetString("LENGTH_COMPRESS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho:.
        /// </summary>
        public static string LENGTH_LABEL {
            get {
                return ResourceManager.GetString("LENGTH_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        public static string LONG_LABEL {
            get {
                return ResourceManager.GetString("LONG_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string LONGITUDE_LABEL {
            get {
                return ResourceManager.GetString("LONGITUDE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faixa de valores inválido.
        /// </summary>
        public static string MGS_RANGE_VALUE_INVALID {
            get {
                return ResourceManager.GetString("MGS_RANGE_VALUE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique em sincronizar dados para obter as atualizações recentes.
        /// </summary>
        public static string MSG_ALERT_SYNC {
            get {
                return ResourceManager.GetString("MSG_ALERT_SYNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronizando dados. Aguarde....
        /// </summary>
        public static string MSG_AWAIT {
            get {
                return ResourceManager.GetString("MSG_AWAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baixar.
        /// </summary>
        public static string MSG_BAIXAR {
            get {
                return ResourceManager.GetString("MSG_BAIXAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados não sincronizados com o servidor. Sincronize os dados antes de efetuar o logout.
        /// </summary>
        public static string MSG_DADOS_NOT_SINC {
            get {
                return ResourceManager.GetString("MSG_DADOS_NOT_SINC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados não sincronizados com o servidor. Sincronize os dados antes de efetuar o logout. Se continuar, todos os dados serão perdidos. Deseja continuar mesmo assim?.
        /// </summary>
        public static string MSG_DADOS_NOT_SINC_QUESTION {
            get {
                return ResourceManager.GetString("MSG_DADOS_NOT_SINC_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados não sincronizados com o servidor: empresa {0} e usuário {1}. Sincronize os dados logando com o usuário anterior. Se continuar, todos os dados serão perdidos. Deseja continuar mesmo assium?.
        /// </summary>
        public static string MSG_DADOS_NOT_SINC_USER_QUESTION {
            get {
                return ResourceManager.GetString("MSG_DADOS_NOT_SINC_USER_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja sincronizar os dados?.
        /// </summary>
        public static string MSG_DADOS_SINC {
            get {
                return ResourceManager.GetString("MSG_DADOS_SINC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados sincronizados com sucesso.
        /// </summary>
        public static string MSG_DADOS_SINC_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_DADOS_SINC_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro excluído com sucesso.
        /// </summary>
        public static string MSG_DELETED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_DELETED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida.
        /// </summary>
        public static string MSG_DELETION_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("MSG_DELETION_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados baixados com sucesso.
        /// </summary>
        public static string MSG_DOWN_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_DOWN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girar.
        /// </summary>
        public static string MSG_GIRAR {
            get {
                return ResourceManager.GetString("MSG_GIRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do arquivo deve ser de {0} MB. Você escolheu um arquivo de {1}.
        /// </summary>
        public static string MSG_MAX_SIZE_FILE_EXCEEDED {
            get {
                return ResourceManager.GetString("MSG_MAX_SIZE_FILE_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo de &apos;{PropertyName}&apos; deve ser de {MaxLength} caracteres.
        /// </summary>
        public static string MSG_MAXIMUM_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("MSG_MAXIMUM_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string MSG_NAO {
            get {
                return ResourceManager.GetString("MSG_NAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem acesso à internet.
        /// </summary>
        public static string MSG_NOT_NETWORKACCESS {
            get {
                return ResourceManager.GetString("MSG_NOT_NETWORKACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habilitar Modo Offline?.
        /// </summary>
        public static string MSG_OFFILE_MODE_ENABLE {
            get {
                return ResourceManager.GetString("MSG_OFFILE_MODE_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo Offline Habilitado.
        /// </summary>
        public static string MSG_OFFLINE_MODE {
            get {
                return ResourceManager.GetString("MSG_OFFLINE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para trabalhar em modo offline deve efetuar uma sincronização completa.
        /// </summary>
        public static string MSG_OFFLINE_MODE_INFO {
            get {
                return ResourceManager.GetString("MSG_OFFLINE_MODE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MSG_OK {
            get {
                return ResourceManager.GetString("MSG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida.
        /// </summary>
        public static string MSG_PASSWORD_WRONG {
            get {
                return ResourceManager.GetString("MSG_PASSWORD_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir acesso à arquivos, fotos e galerias.
        /// </summary>
        public static string MSG_PERMISSIONS_MEDIA {
            get {
                return ResourceManager.GetString("MSG_PERMISSIONS_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um problema inesperado. Entre em contato com administrador.
        /// </summary>
        public static string MSG_PROBLEMA_INESPERADO {
            get {
                return ResourceManager.GetString("MSG_PROBLEMA_INESPERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando aguarde....
        /// </summary>
        public static string MSG_PROCESSING_WAIT {
            get {
                return ResourceManager.GetString("MSG_PROCESSING_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envio de dados pendente. Clique em enviar..
        /// </summary>
        public static string MSG_RECRUTA_PENDENCIA {
            get {
                return ResourceManager.GetString("MSG_RECRUTA_PENDENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório.
        /// </summary>
        public static string MSG_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Campos Obrigatórios.
        /// </summary>
        public static string MSG_REQUIRED_FIELD_INFO {
            get {
                return ResourceManager.GetString("MSG_REQUIRED_FIELD_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao salvar registro.
        /// </summary>
        public static string MSG_SAVED_FAILURE {
            get {
                return ResourceManager.GetString("MSG_SAVED_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro salvo com sucesso.
        /// </summary>
        public static string MSG_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar.
        /// </summary>
        public static string MSG_SELECIONAR {
            get {
                return ResourceManager.GetString("MSG_SELECIONAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione....
        /// </summary>
        public static string MSG_SELECIONE {
            get {
                return ResourceManager.GetString("MSG_SELECIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string MSG_SIM {
            get {
                return ResourceManager.GetString("MSG_SIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro atualizado com sucesso.
        /// </summary>
        public static string MSG_UPDATE_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_UPDATE_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados enviados com sucesso.
        /// </summary>
        public static string MSG_UPLOAD_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_UPLOAD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválidos.
        /// </summary>
        public static string MSG_USERNAME_PASSWORD_WRONG {
            get {
                return ResourceManager.GetString("MSG_USERNAME_PASSWORD_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username não confere.
        /// </summary>
        public static string MSG_USERNAME_WRONG {
            get {
                return ResourceManager.GetString("MSG_USERNAME_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor duplicado. Existe um registro com este valor.
        /// </summary>
        public static string MSG_VALOR_DUPLICADO {
            get {
                return ResourceManager.GetString("MSG_VALOR_DUPLICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde....
        /// </summary>
        public static string MSG_WAIT {
            get {
                return ResourceManager.GetString("MSG_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecrutaPlus.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
    }
}
