//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safety.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FuncionarioResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FuncionarioResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Safety.Domain.Resources.FuncionarioResource", typeof(FuncionarioResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analista (junior, pleno , senior).
        /// </summary>
        public static string ANALISTA_LABEL {
            get {
                return ResourceManager.GetString("ANALISTA_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistente.
        /// </summary>
        public static string ASSISTENTE_LABEL {
            get {
                return ResourceManager.GetString("ASSISTENTE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliar.
        /// </summary>
        public static string AUXILIAR_LABEL {
            get {
                return ResourceManager.GetString("AUXILIAR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO.
        /// </summary>
        public static string CEO_LABEL {
            get {
                return ResourceManager.GetString("CEO_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordenador / Supervisor.
        /// </summary>
        public static string COORDENADOR_SUPERVISOR_LABEL {
            get {
                return ResourceManager.GetString("COORDENADOR_SUPERVISOR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diretor.
        /// </summary>
        public static string DIRETOR_LABEL {
            get {
                return ResourceManager.GetString("DIRETOR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensino Fundamental.
        /// </summary>
        public static string ENSINO_FUNDAMENTAL {
            get {
                return ResourceManager.GetString("ENSINO_FUNDAMENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensino Fundamental Incompleto.
        /// </summary>
        public static string ENSINO_FUNDAMENTAL_INCOMPLETO {
            get {
                return ResourceManager.GetString("ENSINO_FUNDAMENTAL_INCOMPLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensino Médio.
        /// </summary>
        public static string ENSINO_MEDIO {
            get {
                return ResourceManager.GetString("ENSINO_MEDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensino Médio Incompleto.
        /// </summary>
        public static string ENSINO_MEDIO_INCOMPLETO {
            get {
                return ResourceManager.GetString("ENSINO_MEDIO_INCOMPLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensino Superior.
        /// </summary>
        public static string ENSINO_SUPERIOR {
            get {
                return ResourceManager.GetString("ENSINO_SUPERIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensino Superior Incompleto.
        /// </summary>
        public static string ENSINO_SUPERIOR_INCOMPLETO {
            get {
                return ResourceManager.GetString("ENSINO_SUPERIOR_INCOMPLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminino.
        /// </summary>
        public static string GENERO_FEMININO {
            get {
                return ResourceManager.GetString("GENERO_FEMININO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LGBTQIA+.
        /// </summary>
        public static string GENERO_LGBTQIAMAIS {
            get {
                return ResourceManager.GetString("GENERO_LGBTQIAMAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string GENERO_MASCULINO {
            get {
                return ResourceManager.GetString("GENERO_MASCULINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefiro não responder.
        /// </summary>
        public static string GENERO_PREFIRO_NAO_RESPONDER {
            get {
                return ResourceManager.GetString("GENERO_PREFIRO_NAO_RESPONDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargos.
        /// </summary>
        public static string LABEL_CARGOS {
            get {
                return ResourceManager.GetString("LABEL_CARGOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string MSG_ATIVO {
            get {
                return ResourceManager.GetString("MSG_ATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativado.
        /// </summary>
        public static string MSG_OFFLINE {
            get {
                return ResourceManager.GetString("MSG_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro salvo com sucesso.
        /// </summary>
        public static string MSG_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presidente.
        /// </summary>
        public static string PRESIDENTE_LABEL {
            get {
                return ResourceManager.GetString("PRESIDENTE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
    }
}
