//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecrutaPlus.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FuncionarioResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FuncionarioResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecrutaPlus.Domain.Resources.FuncionarioResource", typeof(FuncionarioResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Analista (junior, pleno , senior).
        /// </summary>
        public static string ANALISTA_LABEL {
            get {
                return ResourceManager.GetString("ANALISTA_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assistente.
        /// </summary>
        public static string ASSISTENTE_LABEL {
            get {
                return ResourceManager.GetString("ASSISTENTE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Auxiliar.
        /// </summary>
        public static string AUXILIAR_LABEL {
            get {
                return ResourceManager.GetString("AUXILIAR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEO.
        /// </summary>
        public static string CEO_LABEL {
            get {
                return ResourceManager.GetString("CEO_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coordenador / Supervisor.
        /// </summary>
        public static string COORDENADOR_SUPERVISOR_LABEL {
            get {
                return ResourceManager.GetString("COORDENADOR_SUPERVISOR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novo.
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deletar.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diretor.
        /// </summary>
        public static string DIRETOR_LABEL {
            get {
                return ResourceManager.GetString("DIRETOR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ensino Fundamental.
        /// </summary>
        public static string ENSINO_FUNDAMENTAL {
            get {
                return ResourceManager.GetString("ENSINO_FUNDAMENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ensino Fundamental Incompleto.
        /// </summary>
        public static string ENSINO_FUNDAMENTAL_INCOMPLETO {
            get {
                return ResourceManager.GetString("ENSINO_FUNDAMENTAL_INCOMPLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ensino Médio.
        /// </summary>
        public static string ENSINO_MEDIO {
            get {
                return ResourceManager.GetString("ENSINO_MEDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ensino Médio Incompleto.
        /// </summary>
        public static string ENSINO_MEDIO_INCOMPLETO {
            get {
                return ResourceManager.GetString("ENSINO_MEDIO_INCOMPLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ensino Superior.
        /// </summary>
        public static string ENSINO_SUPERIOR {
            get {
                return ResourceManager.GetString("ENSINO_SUPERIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ensino Superior Incompleto.
        /// </summary>
        public static string ENSINO_SUPERIOR_INCOMPLETO {
            get {
                return ResourceManager.GetString("ENSINO_SUPERIOR_INCOMPLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Feminino.
        /// </summary>
        public static string GENERO_FEMININO {
            get {
                return ResourceManager.GetString("GENERO_FEMININO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LGBTQIA+.
        /// </summary>
        public static string GENERO_LGBTQIAMAIS {
            get {
                return ResourceManager.GetString("GENERO_LGBTQIAMAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Masculino.
        /// </summary>
        public static string GENERO_MASCULINO {
            get {
                return ResourceManager.GetString("GENERO_MASCULINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Prefiro não responder.
        /// </summary>
        public static string GENERO_PREFIRO_NAO_RESPONDER {
            get {
                return ResourceManager.GetString("GENERO_PREFIRO_NAO_RESPONDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargos.
        /// </summary>
        public static string LABEL_CARGOS {
            get {
                return ResourceManager.GetString("LABEL_CARGOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativo.
        /// </summary>
        public static string MSG_ATIVO {
            get {
                return ResourceManager.GetString("MSG_ATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desativado.
        /// </summary>
        public static string MSG_OFFLINE {
            get {
                return ResourceManager.GetString("MSG_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro salvo com sucesso.
        /// </summary>
        public static string MSG_SAVED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("MSG_SAVED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Presidente.
        /// </summary>
        public static string PRESIDENTE_LABEL {
            get {
                return ResourceManager.GetString("PRESIDENTE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
    }
}
